global_must_exclude:
 - "amp"
 - "guard"
 - "copy"
 - "replica"
 - "plate"
 - "bridge"
 - "pickup"
 - "knob"
 - "tuner"
 - "switch"
 - "neck"
 - "body"
 - "bundle"
 - "items"
 - "extra"
 - "left"

guitar_models:
- reference_model: "Fender American Professional II Stratocaster"
  must_include:
    - ["fender"]
    - ["american", "am"]
    - ["professional ii", "professional 2", "pro ii", "pro 2"]
    - ["strat"]
  must_exclude: ["squier", "jazz", "jaguar", "tele", "bass", "bag", "custom", "limited", "ltd", "anniversary", "thinline"]
- reference_model: "Gibson Les Paul Standard 60s"
  must_include:
    - ["gibson"]
    - ["les paul", "lp"]
    - ["standard"]
    - ["60"]
  must_exclude: ["epiphone", "bag", "custom", "faded", "vos", "murphy", "reissue"]