guitar_models:
- reference_model: "Fender American Professional II Stratocaster"
  must_include:
    - ["fender"]
    - ["american", "am"]
    - ["professional II", "professional 2", "pro II", "pro 2"]
    - ["strat"]
  must_exclude: ["squier", "jazz", "jaguar", "tele", "bass", "bag", "case", "amp", "guard", "+", "w/", "w\\", "with", "copy", "replica"]
- reference_model: "Gibson Les Paul Standard 60s"
  must_include:
    - ["gibson"]
    - ["les paul", "lp"]
    - ["standard 60", "standard '60"]
  must_exclude: ["epiphone", "bag", "case", "amp", "guard", "+", "w/", "w\\", "with", "copy", "replica"]